CREATE TABLE  `ponto` (
 `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
 `nome` VARCHAR( 50 ) NULL ,
 `ultimoRegistro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ,
 `disponivel` BOOL NULL DEFAULT  '0',
 `password` VARCHAR(50) NULL

) ENGINE = MYISAM CHARACTER SET latin1 COLLATE latin1_bin;

CREATE TABLE  `sala` (
 `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
 `nome` VARCHAR( 20 ) NULL
) ENGINE = MYISAM CHARACTER SET latin1 COLLATE latin1_bin;
